// *********************************************************************************
// controller.js - this file offers a set of routes for displaying and saving data to the db
// *********************************************************************************

// Dependencies
// =============================================================
// recovery 1020 2020 2:54pm
const axios = require('axios')

// Requiring our models
var db = require("../models");
var nodemailer = require("nodemailer");

// Routes
// =============================================================
module.exports = function (app) {
<<<<<<< HEAD

  // Get route
  app.get("/", function (req, res) {
    res.render("index")
  });

  app.get("/signup", function (req, res) {
    res.render("signup")
  });

  // Get route for all gardens
  app.get("/api/gardens", function (req, res) {
    db.Garden.findAll().then(result => {
      res.json(result);
    })
  })

  // Get route for all composts
  app.get("/api/composts", function (req, res) {
    db.Compost.findAll().then(result => {
      res.json(result);
    })
  })
  // POST route 
  app.post("/email", function (req, res) {
=======
  // Get route
  app.get("/", function (req, res) {
    res.render("index").end();
  });

  app.get("/signup", function(req, res) {
    res.render("signup")
  });
  
   // Get route for all gardens
   app.get("/api/gardens", function(req, res) {
    db.Garden.findAll().then(result=>{
      res.json(result);
    })
  })

  // Get route for all composts
  app.get("/api/composts", function(req, res) {
    db.Compost.findAll().then(result=>{
      res.json(result);
    })
  })

  // POST route
  app.post("/email", function (req, res) {
    db.Owner.findOne({
      where: {
        id: req.body.userId,

      },
    }).then(function (data) {
      //email addresses
>>>>>>> dev

      const newEmail = {
        from: "patchedapp@gmail.com", //can we get from DB using ID?
        to: "chrissakwa@gmail.com", //can we get from DB using ID?
        subject: "testing nodemailer",
        text: "this works as is",
      };

<<<<<<< HEAD
  // Post route to add an Owner
  app.post("/api/owners", function (req, res) {
    const APIKey = '0a157990-f940-11ea-ac04-cb65445966da'
    axios.get(`https://app.geocodeapi.io/api/v1/search?apikey=${APIKey}&text=${req.body.address}`)
      .then(response => {
        db.Owner.create({
          username: req.body.username,
          email: req.body.email,
          address: req.body.address,
          latitude: response.data.bbox[1],
          longitude: response.data.bbox[0],
          password: req.body.password
        }).then(result => {
          res.json(result)
        })
      })
  })


  // Post route to add a garden
  app.post("/api/gardens", function (req, res) {
    db.Owner.findOne({ where: { id: req.params.id } }).then(result => {
      console.log(result)
      db.Garden.create({
        name: req.body.name,
        address: req.body.address,
        latitude: response.data.bbox[1],
        longitude: response.data.bbox[0],
        description: req.body.description,
        length: req.body.length,
        width: req.body.width
        // pictureLink: generated by cloudinary
      }).then(result => {
        res.json(result)
      }
      ).catch(err => {
        res.status(500).send(err)
      })
    })
  })


  // DELETE route 
  app.delete("/", function (req, res) {
=======
      //transportation module

      const transport = nodemailer.createTransport({
        service: "gmail",
        auth: {
          user: "patchedapp@gmail.com",
          pass: "Project2!",
        },
      });
>>>>>>> dev

      //email sending
      transport.sendMail(newEmail, (err, info) => {
        if (err) {
          console.log(err);
        } else {
          console.log("email sent successfully" + info);
        }
      });
    });
    res.json(data);
    // const userType = req.body.userType,
    // const userId = req.body.userId,
    // const emailBody = req.body.emailBody
  });

  app.post("/api/gardens", function(req, res) {
    const APIKey = '0a157990-f940-11ea-ac04-cb65445966da'
    axios.get(`https://app.geocodeapi.io/api/v1/search?apikey=${APIKey}&text=${req.body.address}`)
  .then(response => {
    console.log(response);
    db.Garden.create({
      name: req.body.name,
      address: req.body.address,
      latitude: response.data.bbox[1],
      longitude: response.data.bbox[0],
      description: req.body.description,
      length: req.body.length,
      width: req.body.width
      // pictureLink: generated by cloudinary
    }).then(result=>{
      res.json(result)
    }
    ).catch(err=>{
      res.status(500).send("broken server")
    })
  })
  .catch(error => {
    console.log(error);
  });
  });

  // DELETE route
  app.delete("/", function (req, res) {});

  // PUT route
<<<<<<< HEAD
  app.put("/api/posts", function (req, res) {
=======
  app.put("/api/posts", function (req, res) {});
>>>>>>> dev

};
