// *********************************************************************************
// controller.js - this file offers a set of routes for displaying and saving data to the db
// *********************************************************************************

// Dependencies
// =============================================================



// Requiring our models
var db = require("../models");
var nodemailer = require("nodemailer");

// Routes
// =============================================================
module.exports = function (app) {
 


  
  

  // Compost routes =======================================
  
  // Get all composts
  app.get("/api/composts", function (req, res) {
    db.Compost.findAll().then(result => {
      res.json(result)
    }).catch(err => {
      res.status(500).send(err);
    })
  })

  // Get compost by id
  app.get("/api/composts/:id", function (req, res) {
    db.Garden.findOne({ where: { id: req.params.id } }).then(result => {
      res.json(result)
    }).catch(err => {
      res.status(500).send(err);
    })
  });

  

  // Post route to add a compost
  app.post("/api/composts", function (req, res) {
    db.Owner.findOne({ where: { id: req.body.OwnerId } }).then(owner => {
      db.Compost.create({
        name: req.body.name,
        address: owner.address,
        latitude: owner.latitude,
        longitude: owner.longitude,
        OwnerId: owner.id
        // pictureLink: generated by cloudinary
      }).then(result => {
        res.json(result)
      }
      ).catch(err => {
        res.status(500).send(err)
      })
    }).catch(err => {
      res.status(500).send(err)
    })
  })

//DELETE route to delete compost by ID
app.delete("/api/compost/:id", function(req, res){
  db.Compost.destroy({
    where: {
      id: req.params.id
    }
  }).then(data=>{
    if (data === 0) {
      res.status(404).json(data);
    } else {
      res.json(data);
    }
}).catch(err=>{
  console.log(err);
  res.status(500).json(err);
});
});

  // PUT route
  app.put("/api/composts/:id", function (req, res) { });


  // Email post route ============================
  // POST route to send email
  app.post("/email", function (req, res) {
    db.Owner.findOne({
      where: {
        id: req.body.userId,

      },
    }).then(function (data) {
      //email addresses
      const newEmail = {
        from: "patchedapp@gmail.com", //can we get from DB using ID?
        to: "chrissakwa@gmail.com", //can we get from DB using ID?
        subject: "testing nodemailer",
        text: "this works as is",
      };
      //email sending
      transport.sendMail(newEmail, (err, info) => {
        if (err) {
          console.log(err);
        } else {
          console.log("email sent successfully" + info);
        }
        res.json(data);
        // const userType = req.body.userType,
        // const userId = req.body.userId,
        // const emailBody = req.body.emailBody
      });
    });
  });

}



